#!/usr/bin/env python

import unittest
import io
from mock import Mock
from src.fastq import read_fastq

class TestFastq(unittest.TestCase):

    def get_test_fastq(self):
        result = "@AC326-A:29:000000000-A92C9:1:1101:20529:1320 1:N:0:O243 ACCACTGT|0|TATCCTCT|0\n"
        result += "ACGAAGCTTGAAGGAAATGGCTTTGCTTTTAAGGTACTATGTTCACAGCTTTTCGTGTGAATGCAATCTCATATGTGTAAACCATTGAACGGTGATGTATTTTTAGCTCCAATAAAACTGCACTGATGGTAAAGATCTTATTTAATGTGAACAGTTGGTCACCTTTTGCCTCCTCTATTTGTCATTTCATTGATTCTTCATGTTCATAAGTAGACCAATGCTCTTACCACAAGTGAGATAATATGCTAGTTATGCTGAGCATTGCAGGGGTGGATCACAATTACTGTGGATTGCACCAAGTGGTGGCAGAGATCGTCCAGATCCG\n"
        result += "+\n"
        result += "CCCCCGGGGGGGGGGGGGGFGGDG7GGGGGGGGGGGGGGGGGGGGFFFGBFGGGGFFAFGGGGGEEGGGGGGGGGGGGGFGGGGGGGGGAGEFGFGGFGGGGGGGFFFGFGGGGGGGFFGGGFGGGGGGGGGGFGGGGGGGGGGGDGGGGGFGGGGGFGGGGGGGGGGGGGGGGGGFGFGGGGGGEGGGGGGGFGFFGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGG<GGGGGGGGGGGGGGGGGGFFGGGGGGFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEEGEGGGGGGGGGGGGGGGGGFGGGGCCCCC\n"
        result += "@AC326-A:29:000000000-A92C9:1:1101:12125:1320 1:N:0:O374 ACCACTGT|0|TGAACCTT|0\n"
        result += "TGGCAAGTTTACAAGTGATCAGAGTCTAATATACAATGTAAGTTGCTTACTATGGTTGACTATGAACAAAGCCAACTGCAGTTGCATTAGAAATTAGCTATGAACAAAGGCAACTGCAGTTGCAGTAGAAACTATTACCAAGGTTGTCTGGGTATGTGGATGCAGAGAATGGTGGGACAGTTTTGCTAATCAAATGTTTATTTCCAGTCTCAAAAGCCTGATCATTGGAGTTTTGATCTTTTTGTCGCTTTCTCAGGCTGTACTTCAAGCACATGATGCGGTGATTGCTGCTATGGAACCTGGAGTTAGCTGG\n"
        result += "+\n"
        result += "CCCCCGGGGGGGGGGGGGGGGGGGDFFGGGGFGGGGGGGGGGDGA8EEFEEFGF8CFCEFDFGDGGGGGGFFGGGGGGFGGFFGGGGGGFFGGFFFGGGGGFGFGGGGG?FEFFFGFFFGGGGGGGGGGFFGFGGGGFFFCGFGGGEFFGGGGFEDFEGGGGFGEAFGGGGGFC>EEAGGGGGGGFFCFFGFGGGGGFGGGGFFGGFFGFAGGGGGGFGFFGGGGGGGFGFGGGGGGGGGGGGGGGGFGGGFFFEGGCGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGF?GGGGFGGGGGGGGGGGGCCCCC"
        return result

    def test_read_fastq(self):
        fastq_string = self.get_test_fastq()
        seqs_generator = read_fastq(io.StringIO(fastq_string))
        seqs = []
        for seq in seqs_generator:
            seqs.append(seq)
        self.assertEquals(2, len(seqs))
        expected_header_1 = "AC326-A:29:000000000-A92C9:1:1101:20529:1320 1:N:0:O243 ACCACTGT|0|TATCCTCT|0"
        self.assertEquals(expected_header_1, seqs[0].header)
        


##########################
def suite():
    suite = unittest.TestSuite()
    suite.addTest(unittest.makeSuite(TestFastq))
    return suite

if __name__ == '__main__':
    unittest.main()
